CREATE TABLE IF NOT EXISTS merged_data (
    review_id TEXT PRIMARY KEY,
    company TEXT,
    job_title TEXT,
    department TEXT,
    location TEXT,
    review_date TEXT,
    overall_rating REAL,
    pros TEXT,
    cons TEXT,
    employee_id TEXT,
    name TEXT,
    status TEXT,
    joining_date TEXT,
    exit_date TEXT,
    engagement_score REAL,
    performance_rating INTEGER,
    salary_band TEXT,
    gender TEXT,
    age INTEGER
);
